apiVersion: v1
kind: ConfigMap
metadata:
  name: steampipe-config
  namespace: finops-infra
  labels:
    app: steampipe
data:
  STEAMPIPE_LOG_LEVEL: info
  AWS_REGION: eu-central-1
---
apiVersion: v1
kind: Secret
metadata:
  name: steampipe-secrets
  namespace: finops-infra
  labels:
    app: steampipe
type: Opaque
data:
  STEAMPIPE_DATABASE_PASSWORD: <SET_PASSORD_WITH_BASE64_HERE>
  AWS_ACCESS_KEY_ID: <SET_AWS_ACCESS_KEY_WITH_BASE64_HERE>
  AWS_SECRET_ACCESS_KEY: <SET_AWS_SECRET_ACCESS_KEY_WITH_BASE64_HERE>
